name: initiative_support
description: A Flutter DnD 5e assistant for tracking combat initiative, rounds, hit points, armor class, and temporary statuses.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-375.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  path: ^1.8.3
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/battle.png
    - assets/icons/statuses.png
    - assets/icons/main_icon.png
